version: '3'
services:
  csvserver:
    image: docker.io/infracloudio/csvserver:latest
    container_name: csvserver
    ports:
      - "9393:9300"
    volumes:
      - ./inputFile:/csvserver/inputdata:ro

  prometheus:
    image: prom/prometheus:latest  # Use the Prometheus image
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

